# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Caoutch' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Caoutch
    #pod 'GoogleMaps'
    #pod 'Socket.IO-Client-Swift', '~> 13.3.0'
    pod 'Alamofire', '~> 4.7'
    #pod 'AccountKit', '~> 4.35'
    pod 'Google-Mobile-Ads-SDK'
    #pod 'Stripe'
end
